#!/bin/sh
# Regenerate src/tray_macos_icon.h from the black template SVG.
#
# The menu-bar status item wants an AppKit "template" image: pure black
# shapes on alpha, which macOS recolors for the light/dark menu bar and
# for the highlighted state. The PNGs (18pt + 36px retina) are embedded
# as byte arrays so the icon works from the raw build-dir binary as well
# as from the .app bundle, with no loader or resource-path dependency.
#
# Requires rsvg-convert and xxd. The generated header is checked in, so
# this only needs re-running when data/macos/parla-tray-template.svg
# changes.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SVG="$ROOT/data/macos/parla-tray-template.svg"
OUT="$ROOT/src/tray_macos_icon.h"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

rsvg-convert -w 18 -h 18 "$SVG" -o "$TMP/parla_tray_png_1x"
rsvg-convert -w 36 -h 36 "$SVG" -o "$TMP/parla_tray_png_2x"

{
    echo "/* Generated by scripts/macos/gen-tray-icon.sh — do not edit. */"
    echo "#pragma once"
    echo
    (cd "$TMP" && xxd -i parla_tray_png_1x && xxd -i parla_tray_png_2x) \
        | sed 's/^unsigned/static const unsigned/'
} > "$OUT"

echo "wrote $OUT"
